- name: Test
  hosts: db01
  become: yes

  vars:
    users_dict:
      bjones:
        first_name: Bob
        last_name: Jones
        home_dir: /users/bjones
      acook:
        first_name: Anne
        last_name: Cook
        home_dir: /users/acook

    users_list:
      - username: bjones
        first_name: Bob
        last_name: Jones
        home_dir: /users/bjones
      - username: acook
        first_name: Anne
        last_name: Cook
        home_dir: /users/acook

  tasks:

  - name: Dict - Print user details records
    debug: msg="User {{ item.key }} name is {{ item.value.first_name }}; last name is {{ item.value.last_name }}"
    with_dict: "{{ users_dict }}"
    tags:
      - test2

  - name: Dict - create users
    user:
      name: "{{ item.key }}"
      state: present
    with_dict: "{{ users_dict }}"

  - name: List - Print user details records
    debug: msg="User {{ item.username }} name is {{ item.first_name }}; last name is {{ item.last_name }}"
    with_items: "{{ users_list }}"
    tags:
      - test1

#  - name: List - remove users
#    user:
#      name: "{{ item.username }}"
#      state: absent
#    with_items: "{{ users_list }}"



