- name: Test
  hosts: webserver
  become: yes

  tasks:

  - name: create users
    user:
      name: "{{ item.username }}"
      state: present
    with_items:
      - username: bjones
        first_name: bob
        last_name: jones
        home_dir: /users/bjones
        password: secret1
      - username: acook
        first_name: anne
        last_name: cook
        home_dir: /users/acook
        password: secret2
    tags:
      - create_users


